import { LocationItem } from './types';

export const INITIAL_NITW_LOCATIONS: LocationItem[] = [
  // Hostels
  {
    id: 'hostel-1',
    name: '1.8K Hostel (Mega Hostel)',
    category: 'Hostels',
    lat: 17.9848,
    lng: 79.5325,
    description: 'Mega Hostel (1.8K capacity) for B.Tech senior students with high-speed Wi-Fi and amenities.',
  },
  {
    id: 'hostel-2',
    name: 'ALC Hostel',
    category: 'Hostels',
    lat: 17.9835,
    lng: 79.5310,
    description: 'Asian Liberation Club hostel block located close to IFC mess.',
  },
  {
    id: 'hostel-3',
    name: 'Hostel A',
    category: 'Hostels',
    lat: 17.9828,
    lng: 79.5332,
    description: 'B.Tech student accommodation block with central courtyard.',
  },
  {
    id: 'hostel-4',
    name: 'Hostel B',
    category: 'Hostels',
    lat: 17.9822,
    lng: 79.5340,
    description: 'Hostel block B near the sports arena and outdoor courts.',
  },
  {
    id: 'hostel-5',
    name: 'Priyadarshini Ladies Hostel (LH)',
    category: 'Hostels',
    lat: 17.9815,
    lng: 79.5265,
    description: 'Secure women residential complex with green courtyards.',
  },
  {
    id: 'hostel-6',
    name: 'Sarojini Ladies Hostel',
    category: 'Hostels',
    lat: 17.9821,
    lng: 79.5270,
    description: 'Ladies hostel block adjacent to LH dining hall.',
  },
  {
    id: 'hostel-7',
    name: 'Vikram Sarabhai PG Hostel',
    category: 'Hostels',
    lat: 17.9842,
    lng: 79.5345,
    description: 'Postgraduate (M.Tech) and Research Scholar residential quarters.',
  },

  // Mess
  {
    id: 'mess-1',
    name: 'IFC A (International Food Court A)',
    category: 'Mess',
    lat: 17.9840,
    lng: 79.5320,
    description: 'Main dining hall serving vegetarian and non-vegetarian menus.',
  },
  {
    id: 'mess-2',
    name: 'IFC B (Food Court B)',
    category: 'Mess',
    lat: 17.9843,
    lng: 79.5315,
    description: 'Mess facility catering primarily to 1st & 2nd year students.',
  },
  {
    id: 'mess-3',
    name: 'IFC C (Food Court C)',
    category: 'Mess',
    lat: 17.9837,
    lng: 79.5328,
    description: 'Dining hall with South & North Indian culinary counters.',
  },
  {
    id: 'mess-4',
    name: 'Ladies Hostel Mess',
    category: 'Mess',
    lat: 17.9818,
    lng: 79.5268,
    description: 'Dedicated dining hall and breakfast lounge for LH residents.',
  },

  // Academic & Departments
  {
    id: 'dept-1',
    name: 'Central Building (Admin Block)',
    category: 'Departments',
    lat: 17.9782,
    lng: 79.5318,
    description: "Director's office, Registrar, Dean Academics, and Senate hall.",
  },
  {
    id: 'dept-2',
    name: 'Central Library',
    category: 'Departments',
    lat: 17.9790,
    lng: 79.5308,
    description: 'State-of-the-art 3-storey digital library with reading halls and e-journals.',
  },
  {
    id: 'dept-3',
    name: 'Dept of Computer Science & Engineering (CSE)',
    category: 'Departments',
    lat: 17.9775,
    lng: 79.5298,
    description: 'Department of CSE, AI & Data Science labs, and High Performance Computing center.',
  },
  {
    id: 'dept-4',
    name: 'Dept of Electrical & Electronics Engineering (EEE)',
    category: 'Departments',
    lat: 17.9770,
    lng: 79.5312,
    description: 'EEE department, Smart Grid lab, and Power Electronics facilities.',
  },
  {
    id: 'dept-5',
    name: 'Dept of Electronics & Communication (ECE)',
    category: 'Departments',
    lat: 17.9780,
    lng: 79.5290,
    description: 'ECE department, VLSI design suite, and IoT development laboratory.',
  },
  {
    id: 'dept-6',
    name: 'Dept of Mechanical Engineering',
    category: 'Departments',
    lat: 17.9765,
    lng: 79.5325,
    description: 'Mechanical workshop, Robotics research lab, and CAD/CAM center.',
  },
  {
    id: 'dept-7',
    name: 'Dept of Civil Engineering',
    category: 'Departments',
    lat: 17.9760,
    lng: 79.5310,
    description: 'Civil Engineering department, Geotechnical lab, and Heritage structure.',
  },
  {
    id: 'dept-8',
    name: 'Dept of Chemical Engineering',
    category: 'Departments',
    lat: 17.9758,
    lng: 79.5332,
    description: 'Chemical process engineering labs and petroleum research center.',
  },
  {
    id: 'dept-9',
    name: 'Dept of Biotechnology',
    category: 'Departments',
    lat: 17.9752,
    lng: 79.5320,
    description: 'Biotechnology laboratories, genetics suite, and bio-incubation cell.',
  },

  // Others & Landmarks
  {
    id: 'other-1',
    name: 'Taza Food Court',
    category: 'Others',
    lat: 17.9796,
    lng: 79.5302,
    description: 'Popular campus cafeteria serving fresh meals, shakes, and beverages.',
  },
  {
    id: 'other-2',
    name: 'NITW Main Entrance Gate',
    category: 'Others',
    lat: 17.9750,
    lng: 79.5285,
    description: 'Main Entrance Gate on Kazipet-Warangal Highway with security post.',
  },
  {
    id: 'other-3',
    name: 'Student Activity Centre (SAC)',
    category: 'Others',
    lat: 17.9802,
    lng: 79.5330,
    description: 'Hub for student clubs, indoor badminton courts, gym, and music room.',
  },
  {
    id: 'other-4',
    name: 'NITW Sports Stadium & Athletics Track',
    category: 'Others',
    lat: 17.9810,
    lng: 79.5350,
    description: 'Multi-purpose stadium, cricket pavilion, and synthetic tennis courts.',
  },
  {
    id: 'other-5',
    name: 'Campus Health Centre (Dispensary)',
    category: 'Others',
    lat: 17.9808,
    lng: 79.5295,
    description: '24/7 campus hospital offering medical care, pharmacy, and ambulance.',
  },
  {
    id: 'other-6',
    name: 'Innovation Garage (IG)',
    category: 'Others',
    lat: 17.9788,
    lng: 79.5322,
    description: 'Student-run makerspace, 3D printing lab, and startup incubator.',
  },
];
